import { Platform, StyleSheet } from "react-native";
import type { ThemePalette } from "../domain/types";
import {
  CHAT_BUBBLE_BODY_SIZE,
  CHAT_HEADER_SIDE_RAIL_WIDTH,
  CHAT_XH,
  CHAT_XH_HALF,
  ONLINE_GREEN,
  ONLINE_STRIP_EDGE_PAD,
  ONLINE_VISIBLE_SLOTS,
} from "../theme/preludeConstants";

export const makeStyles = (theme: ThemePalette) =>
  StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: theme.background,
      paddingHorizontal: 14,
    },
    offlineBanner: {
      position: "absolute",
      left: 0,
      right: 0,
      zIndex: 100001,
      elevation: 100001,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingVertical: 8,
      paddingHorizontal: 12,
      backgroundColor: "rgba(180, 60, 40, 0.92)",
    },
    offlineBannerText: {
      color: "#FFFFFF",
      fontSize: 13,
      fontWeight: "600",
    },
    screenRoot: {
      flex: 1,
      paddingHorizontal: 14,
    },
    homeColumn: {
      flex: 1,
      minHeight: 0,
    },
    /** Fills below the home top bar; swipe-right opens friends (PanResponder). */
    homeMainSwipeLayer: {
      flex: 1,
      minHeight: 0,
    },
    homeBottomChrome: {
      backgroundColor: theme.background,
    },
    homeBottomChromeTransparent: {
      backgroundColor: "transparent",
      marginHorizontal: -14,
      paddingHorizontal: 14,
    },
    bottomDeadZone: {
      backgroundColor: theme.background,
      marginHorizontal: -14,
    },
    chatListFlex: {
      flex: 1,
      minHeight: 0,
    },
    /** Full-bleed wrapper: cancels `screenRoot` horizontal padding for the online strip. */
    onlineStripOuter: {
      marginHorizontal: -14,
      alignSelf: "stretch",
    },
    /**
     * Same width as six equal slots (`windowWidth - 28`). Overflow clips so column 7+ is not visible at scroll 0.
     */
    onlineStripClip: {
      marginHorizontal: ONLINE_STRIP_EDGE_PAD,
      overflow: "hidden",
      height: 78,
    },
    onlineStripList: {
      flexGrow: 0,
      flexShrink: 0,
      height: 78,
    },
    onlineStripEmpty: {
      color: theme.subtleText,
      fontSize: 13,
      paddingVertical: 8,
      paddingHorizontal: 14,
    },
    fullScreen: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: theme.background,
      zIndex: 20,
      paddingHorizontal: 14,
    },
    center: {
      justifyContent: "center",
      alignItems: "center",
      gap: 12,
    },
    largeText: {
      color: theme.text,
      fontSize: 24,
      fontWeight: "700",
    },
    authModeRow: {
      flexDirection: "row",
      gap: 8,
      marginBottom: 12,
    },
    authModeButton: {
      flex: 1,
      borderWidth: 1,
      borderColor: theme.divider,
      borderRadius: 10,
      paddingVertical: 10,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.background,
    },
    authModeButtonActive: {
      borderColor: theme.accent,
      backgroundColor: `${theme.accent}18`,
    },
    authModeButtonText: {
      color: theme.subtleText,
      fontSize: 14,
      fontWeight: "700",
    },
    authModeButtonTextActive: {
      color: theme.accent,
    },
    authCard: {
      gap: 10,
      paddingBottom: 20,
    },
    authLoginRoot: {
      flex: 1,
    },
    authTopBar: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 8,
    },
    authTopSideSpacer: {
      width: 64,
      height: 36,
    },
    authTopLinkButton: {
      minWidth: 64,
      height: 36,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 8,
    },
    authTopLinkText: {
      color: theme.subtleText,
      fontWeight: "800",
      fontSize: 14,
    },
    authCentered: {
      flex: 1,
      justifyContent: "center",
    },
    authHeading: {
      color: theme.text,
      fontSize: 22,
      fontWeight: "800",
      marginBottom: 4,
    },
    homeTopBar: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 10,
    },
    homeTopLeftIcons: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    homeModeIconActive: {
      backgroundColor: `${theme.accent}1F`,
    },
    feedListFullBleed: {
      marginHorizontal: -14,
    },
    feedList: {
      paddingTop: 4,
      paddingBottom: 8,
      flexGrow: 1,
    },
    feedEmpty: {
      color: theme.subtleText,
      fontSize: 14,
      textAlign: "center",
      marginTop: 24,
    },
    feedSeparator: {
      height: 10,
    },
    postFeedCard: {
      paddingVertical: 10,
      paddingHorizontal: 14,
    },
    postFeedHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginBottom: 8,
    },
    postFeedHeaderTextCol: {
      flex: 1,
      minWidth: 0,
    },
    postFeedHeaderAction: {
      width: 30,
      height: 30,
      borderRadius: 15,
      alignItems: "center",
      justifyContent: "center",
    },
    postFeedAuthor: {
      color: theme.text,
      fontSize: 15,
      fontWeight: "700",
    },
    postFeedTime: {
      color: theme.subtleText,
      fontSize: 12,
      marginTop: 2,
    },
    postFeedBodyWrap: {
      position: "relative",
      marginBottom: 8,
    },
    postFeedBody: {
      color: theme.text,
      fontSize: 15,
      lineHeight: 21,
    },
    postFeedMediaWrap: {
      marginHorizontal: -14,
      marginBottom: 8,
      backgroundColor: "#000000",
      position: "relative",
      borderRadius: 0,
      overflow: "visible",
    },
    feedReactCornerFab: {
      position: "absolute",
      right: 12,
      bottom: 12,
      zIndex: 6,
      elevation: 6,
    },
    postFeedImageStrip: {
      width: "100%",
    },
    postFeedImageFullWidth: {
      width: "100%",
      backgroundColor: "#000000",
      borderRadius: 0,
    },
    postFeedImageSlide: {
      backgroundColor: "#000000",
      borderRadius: 0,
      overflow: "hidden",
      justifyContent: "center",
    },
    postFeedVideoWrap: {
      position: "relative",
      marginHorizontal: -14,
      marginBottom: 8,
      backgroundColor: "#000000",
      borderRadius: 0,
      overflow: "visible",
    },
    postFeedVideo: {
      width: "100%" as const,
      backgroundColor: "#000000",
    },
    feedReactionHost: {
      width: "100%",
    },
    privateCommentBubbleColumn: {
      alignSelf: "flex-start",
      maxWidth: "92%",
    },
    privateCommentBubbleColumnRight: {
      alignSelf: "flex-end",
    },
    privateCommentBubble: {
      alignSelf: "flex-start",
      maxWidth: "92%",
      borderRadius: 12,
      paddingHorizontal: 10,
      paddingVertical: 8,
      marginTop: 4,
      backgroundColor:
        theme.background === "#000000" ? "rgba(255,255,255,0.06)" : `${theme.divider}88`,
    },
    messageReactionHost: {
      maxWidth: "85%",
      alignSelf: "flex-start",
    },
    messageReactionHostMine: {
      alignSelf: "flex-end",
    },
    feedReactionChipActive: {
      borderWidth: 1,
      borderColor: theme.accent,
    },
    readReceiptAvatarRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      gap: 4,
      marginTop: 2,
      marginBottom: 2,
      width: "100%",
    },
    messageBlock: {
      width: "100%",
      marginBottom: 12,
    },
    messageBlockRow: {
      marginBottom: 0,
    },
    feedReactionSummaryChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
      paddingHorizontal: 9,
      paddingVertical: 5,
      borderRadius: 14,
      backgroundColor:
        theme.background === "#000000" ? "rgba(255,255,255,0.08)" : `${theme.divider}cc`,
    },
    feedReactionSummaryEmoji: {
      fontSize: 16,
    },
    feedReactionSummaryCount: {
      fontSize: 12,
      fontWeight: "700",
      color: theme.subtleText,
    },
    feedCommentActionRow: {
      marginTop: 8,
      minHeight: 32,
      flexDirection: "row",
      alignItems: "center",
    },
    feedCommentActionButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 12,
      backgroundColor:
        theme.background === "#000000" ? "rgba(255,255,255,0.06)" : `${theme.divider}aa`,
    },
    feedCommentActionText: {
      color: theme.subtleText,
      fontSize: 12,
      fontWeight: "600",
    },
    postCommentPlaceholderBar: {
      marginHorizontal: 12,
      marginTop: 10,
      paddingHorizontal: 14,
      paddingVertical: 11,
      borderRadius: 12,
      backgroundColor:
        theme.background === "#000000" ? "rgba(255,255,255,0.06)" : `${theme.divider}99`,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.divider,
    },
    postCommentPlaceholderText: {
      color: theme.subtleText,
      fontSize: 15,
      fontWeight: "500",
    },
    reactionDetailModalRoot: {
      flex: 1,
      justifyContent: "center",
      paddingHorizontal: 22,
    },
    reactionDetailModalBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(0,0,0,0.48)",
    },
    reactionDetailModalCard: {
      maxHeight: "72%",
      borderRadius: 14,
      overflow: "hidden",
      zIndex: 2,
      elevation: 6,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.divider,
    },
    reactionDetailModalHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.divider,
    },
    reactionDetailModalTitle: {
      color: theme.text,
      fontSize: 17,
      fontWeight: "700",
      flex: 1,
    },
    reactionDetailModalList: {
      maxHeight: 360,
    },
    reactionDetailModalEmpty: {
      paddingVertical: 18,
      paddingHorizontal: 14,
    },
    reactionDetailModalRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.divider,
    },
    reactionDetailModalName: {
      flex: 1,
      minWidth: 0,
      color: theme.text,
      fontSize: 15,
      fontWeight: "600",
    },
    reactionDetailModalEmoji: {
      fontSize: 22,
    },
    privateCommentComposerRow: {
      paddingHorizontal: 12,
      paddingTop: 10,
      gap: 8,
    },
    privateCommentComposerInput: {
      marginBottom: 0,
    },
    privateCommentCard: {
      marginHorizontal: 12,
      marginBottom: 10,
      padding: 10,
      borderRadius: 12,
      backgroundColor: theme.background === "#000000" ? "rgba(255,255,255,0.05)" : `${theme.divider}66`,
    },
    privateCommentInlineSection: {
      marginTop: 8,
      gap: 8,
    },
    privateCommentChainHeader: {
      gap: 2,
      marginBottom: 6,
    },
    privateCommentChainName: {
      color: theme.text,
      fontSize: 14,
      fontWeight: "700",
    },
    privateCommentChainPreview: {
      color: theme.subtleText,
      fontSize: 12,
    },
    privateCommentThreadPlain: {
      gap: 8,
    },
    privateCommentPlainRow: {
      gap: 4,
    },
    privateCommentPlainRowRight: {
      alignItems: "flex-end",
    },
    privateCommentAuthorLine: {
      color: theme.text,
      fontSize: 14,
      fontWeight: "700",
    },
    privateCommentTimeLine: {
      color: theme.subtleText,
      fontSize: 11,
    },
    privateCommentSyncLine: {
      color: theme.subtleText,
      fontSize: 11,
      fontStyle: "italic",
    },
    privateCommentSyncFailed: {
      color: "#c0392b",
    },
    privateCommentMeta: {
      color: theme.subtleText,
      fontSize: 11,
      marginBottom: 4,
    },
    privateCommentBody: {
      color: theme.text,
      fontSize: 14,
      lineHeight: 19,
    },
    privateCommentControlsRow: {
      marginTop: 8,
      flexDirection: "row",
      alignItems: "center",
    },
    privateThreadEntry: {
      marginTop: 8,
      marginLeft: 12,
      paddingLeft: 10,
      borderLeftWidth: 2,
      borderLeftColor: theme.divider,
      gap: 4,
    },
    privateThreadBody: {
      color: theme.text,
      fontSize: 13,
      lineHeight: 18,
    },
    privateThreadComposerRow: {
      marginTop: 10,
      marginLeft: 12,
      gap: 8,
    },
    privateThreadComposerInput: {
      marginBottom: 0,
    },
    fullScreenPostRoot: {
      flex: 1,
    },
    fullScreenPostHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 6,
      paddingBottom: 8,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.divider,
    },
    fullScreenPostScroll: {
      flex: 1,
    },
    postCarouselChevron: {
      position: "absolute",
      top: "50%",
      marginTop: -18,
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: "rgba(0,0,0,0.42)",
      alignItems: "center",
      justifyContent: "center",
    },
    postCarouselChevronLeft: {
      left: 10,
    },
    postCarouselChevronRight: {
      right: 10,
    },
    postCarouselCountBadge: {
      position: "absolute",
      right: 10,
      bottom: 10,
      backgroundColor: "rgba(0,0,0,0.55)",
      borderRadius: 12,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    postCarouselCountText: {
      color: "#FFFFFF",
      fontSize: 12,
      fontWeight: "700",
    },
    profilePostsSection: {
      alignSelf: "stretch",
      marginTop: 18,
      paddingBottom: 24,
    },
    profilePostsHeading: {
      color: theme.text,
      fontSize: 16,
      fontWeight: "800",
      marginBottom: 10,
    },
    postGridRow: {
      flexDirection: "row",
      alignItems: "flex-start",
    },
    postGridCell: {
      borderRadius: 10,
      overflow: "hidden",
      backgroundColor: theme.divider,
      position: "relative",
    },
    /** Profile / shared-media post list — same full-bleed width as home feed. */
    profilePostsFeedList: {
      marginHorizontal: -14,
      alignSelf: "stretch",
    },
    profileFeedLoadMoreBtn: {
      alignSelf: "center",
      marginTop: 8,
      marginBottom: 4,
      paddingVertical: 10,
      paddingHorizontal: 16,
    },
    profileFeedLoadMoreText: {
      color: theme.accent,
      fontSize: 14,
      fontWeight: "600",
    },
    postGridImage: {
      width: "100%",
      height: "100%",
    },
    postGridTextMiniWrap: {
      flex: 1,
      paddingHorizontal: 4,
      paddingVertical: 4,
      justifyContent: "flex-start",
    },
    postGridTextMini: {
      color: theme.text,
      fontSize: 9,
      lineHeight: 11,
    },
    postGridEmpty: {
      alignItems: "center",
      justifyContent: "center",
    },
    postGridPlayBadge: {
      position: "absolute",
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "rgba(0,0,0,0.25)",
    },
    chatVideoPlayButton: {
      width: 56,
      height: 56,
      borderRadius: 28,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "rgba(0,0,0,0.45)",
      paddingLeft: 4,
    },
    postComposerOverlay: {
      flex: 1,
    },
    postComposerCard: {
      maxWidth: 420,
      width: "100%",
    },
    postComposerTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    postComposerInput: {
      borderWidth: 1,
      borderColor: theme.divider,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      color: theme.text,
      minHeight: 96,
      textAlignVertical: "top",
      marginBottom: 10,
    },
    postComposerPreviewRow: {
      marginBottom: 10,
    },
    postComposerThumb: {
      width: 72,
      height: 72,
      borderRadius: 8,
      marginRight: 8,
      backgroundColor: theme.divider,
    },
    publishMediaSlot: {
      minHeight: 200,
      borderRadius: 14,
      borderWidth: StyleSheet.hairlineWidth,
      overflow: "hidden",
      justifyContent: "center",
    },
    publishPostCaption: {
      flex: 1,
      minHeight: 140,
      marginTop: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      textAlignVertical: "top",
    },
    publishPostFooterRow: {
      flexDirection: "row",
      gap: 12,
      marginTop: 16,
      alignItems: "stretch",
    },
    /** Icon-only secondary action used inside the new-post media tray. Keeps
     *  the row compact and visually consistent with the editor's icon buttons. */
    iconActionPill: {
      minHeight: 44,
      minWidth: 56,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.background,
    },
    publishPostPublishButton: {
      flex: 1,
      minHeight: 48,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: theme.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    publishPostCancelButton: {
      flex: 1,
      minHeight: 48,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderWidth: 2,
      borderColor: theme.accent,
      backgroundColor: theme.background,
      alignItems: "center",
      justifyContent: "center",
    },
    publishPostPublishButtonText: {
      color: "#FFFFFF",
      fontWeight: "700",
      fontSize: 16,
      lineHeight: 22,
    },
    publishPostCancelButtonText: {
      color: theme.accent,
      fontWeight: "700",
      fontSize: 16,
      lineHeight: 22,
    },
    postComposerActions: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 6,
    },
    iconButton: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: "center",
      justifyContent: "center",
    },
    onlineFriendItem: {
      alignItems: "center",
    },
    profileCircleWrap: {
      marginBottom: 2,
    },
    onlineFriendName: {
      color: theme.text,
      fontSize: 12,
      textAlign: "center",
    },
    chatList: {
      paddingTop: 0,
      paddingBottom: 8,
      flexGrow: 0,
    },
    chatRowBlock: {
      width: "100%",
    },
    /** Matches `broadcastChatRow` borderRadius so dividers don’t extend into the curved corners. */
    broadcastChatRowBlock: {
      marginBottom: 8,
    },
    chatRowSeparator: {
      alignSelf: "stretch",
      height: StyleSheet.hairlineWidth,
      marginHorizontal: 12,
      backgroundColor: theme.divider,
    },
    chatRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 10,
      minHeight: 64,
      /** Reserves the same left edge as broadcast rows so avatars line up vertically. */
      borderLeftWidth: 6,
      borderLeftColor: "transparent",
    },
    broadcastChatRow: {
      backgroundColor: `${theme.accent}42`,
      borderTopWidth: 1,
      borderRightWidth: 1,
      borderBottomWidth: 1,
      borderColor: `${theme.accent}88`,
      /** No accent stripe on the left; keep spacer transparent like other rows. */
      borderLeftColor: "transparent",
      borderRadius: 12,
      paddingVertical: 6,
    },
    broadcastBadge: {
      alignSelf: "flex-start",
      backgroundColor: theme.accent,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 3,
      marginBottom: 4,
    },
    broadcastBadgeText: {
      color: "#FFFFFF",
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 0.3,
      textTransform: "uppercase",
    },
    broadcastChatTitle: {
      color: theme.accent,
      fontSize: 15,
      fontWeight: "800",
    },
    chatTapCard: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      minHeight: 42,
    },
    chatAvatarWrap: {
      position: "relative",
      marginRight: 10,
      width: 42,
      alignItems: "center",
      justifyContent: "center",
    },
    chatAvatar: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: theme.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    chatAvatarText: {
      color: "#FFFFFF",
      fontWeight: "700",
      fontSize: 18,
    },
    onlineDot: {
      position: "absolute",
      width: 12,
      height: 12,
      borderRadius: 6,
      right: -1,
      bottom: -1,
      borderWidth: 2,
      borderColor: theme.background,
      backgroundColor: ONLINE_GREEN,
    },
    chatTextWrap: {
      flex: 1,
      marginRight: 8,
    },
    chatTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginBottom: 2,
      minWidth: 0,
    },
    chatTitleTextFlex: {
      flex: 1,
      minWidth: 0,
    },
    chatMutedIcon: {
      flexShrink: 0,
    },
    chatName: {
      color: theme.text,
      fontSize: 15,
      fontWeight: "600",
    },
    chatNameUnread: {
      fontWeight: "800",
    },
    chatPreview: {
      color: theme.subtleText,
      fontSize: 13,
    },
    chatPreviewUnread: {
      color: theme.text,
      fontWeight: "700",
    },
    chatUnreadDot: {
      width: 9,
      height: 9,
      borderRadius: 5,
      backgroundColor: theme.accent,
      flexShrink: 0,
    },
    chatTimestamp: {
      color: theme.subtleText,
      fontSize: 11,
      marginRight: 12,
      marginTop: 1,
    },
    startChatButton: {
      backgroundColor: theme.accent,
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 8,
    },
    startChatButtonInset: {
      marginHorizontal: 0,
    },
    startChatButtonText: {
      color: "#FFFFFF",
      fontWeight: "700",
      fontSize: 15,
    },
    feedFabButton: {
      position: "absolute",
      left: 14,
      right: 14,
      bottom: 10,
      backgroundColor: theme.accent,
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 8,
      elevation: 5,
    },
    chatScreen: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: theme.background,
      zIndex: 10,
      paddingHorizontal: 14,
    },
    friendsListRoot: {
      flex: 1,
      paddingHorizontal: 14,
    },
    friendsListTitle: {
      flex: 1,
      color: theme.text,
      fontSize: 20,
      fontWeight: "700",
      textAlign: "center",
    },
    friendsListSearch: {
      marginBottom: 10,
    },
    friendsListScroll: {
      flex: 1,
      minHeight: 0,
    },
    friendsListRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 10,
      gap: 12,
    },
    friendsListAvatarWrap: {
      width: 44,
      height: 44,
      alignItems: "center",
      justifyContent: "center",
      position: "relative",
    },
    feedMuteBadge: {
      position: "absolute",
      right: -2,
      bottom: -2,
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: theme.danger,
      borderWidth: 1,
      borderColor: theme.background,
      alignItems: "center",
      justifyContent: "center",
    },
    friendsListName: {
      flex: 1,
      minWidth: 0,
      color: theme.text,
      fontSize: 16,
      fontWeight: "600",
    },
    chatHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 8,
    },
    chatHeaderSideRail: {
      width: CHAT_HEADER_SIDE_RAIL_WIDTH,
      flexDirection: "row",
      alignItems: "center",
    },
    chatHeaderSideRailLeft: {
      gap: 8,
    },
    chatHeaderSideRailRight: {
      justifyContent: "flex-end",
    },
    chatHeaderTitleRail: {
      flex: 1,
      minWidth: 0,
      height: 34,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 4,
    },
    chatHeaderAvatarBubble: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.accent,
    },
    chatHeaderAvatarText: {
      color: "#FFFFFF",
      fontWeight: "700",
      fontSize: 16,
    },
    chatHeaderTitlePressable: {
      width: "100%",
      /** Match `renderAvatar(..., 34)` / `chatHeaderAvatarBubble` so title sits on same vertical band. */
      height: 34,
      justifyContent: "center",
      alignItems: "center",
    },
    /** Header only: no `flex: 1` on Text (avoids the label riding high vs the avatar). */
    chatHeaderTitleText: {
      width: "100%",
      color: theme.text,
      fontSize: 20,
      fontWeight: "700",
      textAlign: "center",
      lineHeight: 22,
      ...Platform.select({
        android: { includeFontPadding: false },
        default: {},
      }),
    },
    chatScreenTitle: {
      flex: 1,
      color: theme.text,
      fontSize: 20,
      fontWeight: "700",
      textAlign: "center",
    },
    profileHeaderTitle: {
      flex: 1,
      color: theme.text,
      fontSize: 18,
      fontWeight: "700",
      textAlign: "center",
    },
    profileScreenHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    headerSpacer: {
      width: 38,
      height: 38,
    },
    headerTitleFlex: {
      flex: 1,
    },
    friendProfileScroll: {
      paddingBottom: 120,
    },
    /** Portrait frame for profile hero photos (width:height = 3:4). */
    friendHeroImageFrame: {
      width: "100%",
      aspectRatio: 3 / 4,
      borderRadius: 12,
      overflow: "hidden",
      backgroundColor: theme.divider,
      marginBottom: 16,
    },
    friendHeroImageFill: {
      width: "100%",
      height: "100%",
    },
    myProfilePlaceholder: {
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    friendHeroName: {
      color: theme.text,
      fontSize: 24,
      fontWeight: "700",
      marginBottom: 8,
    },
    friendHeroBio: {
      color: theme.text,
      fontSize: 15,
      lineHeight: 22,
      marginBottom: 8,
    },
    friendHeroStatus: {
      color: theme.subtleText,
      fontSize: 14,
    },
    profileBottomBar: {
      borderTopWidth: 1,
      borderTopColor: theme.divider,
      paddingTop: 12,
    },
    secondaryButton: {
      alignSelf: "flex-start",
      marginBottom: 16,
      paddingVertical: 6,
    },
    secondaryButtonText: {
      color: theme.accent,
      fontWeight: "600",
      fontSize: 15,
    },
    searchInput: {
      borderWidth: 1,
      borderColor: theme.divider,
      borderRadius: 10,
      color: theme.text,
      paddingHorizontal: 12,
      paddingVertical: 9,
      marginBottom: 10,
    },
    passwordInputRow: {
      flexDirection: "row",
      alignItems: "center",
    },
    passwordInputField: {
      flex: 1,
      marginBottom: 0,
    },
    passwordVisibilityButton: {
      marginLeft: 8,
      width: 40,
      height: 40,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.divider,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 10,
    },
    messageList: {
      paddingTop: 4,
      paddingBottom: 8,
    },
    messageRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      marginBottom: 12,
    },
    messageRowOther: {
      flexDirection: "row",
      alignItems: "flex-start",
      marginBottom: 12,
      width: "100%",
    },
    messageRowMine: {
      flexDirection: "row-reverse",
      alignItems: "flex-start",
      marginBottom: 12,
      width: "100%",
    },
    /** Padded halo behind avatar + bubble when this row is the active reply target. */
    replyTargetRowHalo: {
      borderRadius: 14,
      paddingVertical: 5,
      paddingHorizontal: 4,
    },
    messageAvatar: {
      marginRight: 8,
      marginTop: 2,
      width: 30,
      alignItems: "center",
    },
    messageAvatarOther: {
      marginRight: 8,
      marginTop: 2,
      width: 30,
      alignItems: "center",
    },
    messageAvatarMine: {
      marginLeft: 8,
      marginRight: 0,
      marginTop: 2,
      width: 30,
      alignItems: "center",
    },
    messageColumn: {
      flex: 1,
      minWidth: 0,
      alignItems: "flex-start",
    },
    messageColumnMine: {
      flex: 1,
      minWidth: 0,
      alignItems: "flex-end",
    },
    messageCard: {
      alignSelf: "flex-start",
      maxWidth: "85%",
      borderRadius: 12,
      paddingHorizontal: 10,
      paddingTop: CHAT_XH,
      paddingBottom: CHAT_XH,
      borderWidth: 1,
      borderColor: theme.divider,
      position: "relative",
    },
    myMessageCard: {
      alignSelf: "flex-end",
      backgroundColor: theme.mineBubbleBackground,
      borderColor: "transparent",
    },
    otherMessageCard: {
      backgroundColor: theme.background,
    },
    messageSender: {
      color: theme.text,
      fontSize: 12,
      fontWeight: "700",
      marginBottom: 2,
    },
    messageSenderOutside: {
      color: theme.text,
      fontSize: 12,
      fontWeight: "700",
      marginBottom: 4,
      marginLeft: 2,
    },
    messageSenderOutsideMine: {
      color: theme.text,
      fontSize: 12,
      fontWeight: "700",
      marginBottom: 4,
      marginRight: 2,
      textAlign: "right",
      alignSelf: "stretch",
    },
    messageText: {
      color: theme.text,
      fontSize: CHAT_BUBBLE_BODY_SIZE,
      lineHeight: Math.round(CHAT_BUBBLE_BODY_SIZE * 1.35),
      marginBottom: 0,
    },
    messageTextMine: {
      color: theme.mineBubbleText,
      fontSize: CHAT_BUBBLE_BODY_SIZE,
      lineHeight: Math.round(CHAT_BUBBLE_BODY_SIZE * 1.35),
      marginBottom: 0,
    },
    messageSystemText: {
      color: theme.subtleText,
      fontSize: 14,
      lineHeight: Math.round(14 * 1.35),
      marginBottom: 0,
      fontStyle: "italic",
    },
    messageSystemTextMine: {
      color: theme.subtleText,
      fontSize: 14,
      lineHeight: Math.round(14 * 1.35),
      marginBottom: 0,
      fontStyle: "italic",
    },
    unsentMessageCard: {
      backgroundColor: theme.background,
      borderColor: theme.divider,
      borderWidth: StyleSheet.hairlineWidth,
    },
    unsentMessageCardMine: {
      alignSelf: "flex-end",
    },
    unsentMessageCardOther: {
      alignSelf: "flex-start",
    },
    replyPreviewLine: {
      color: theme.subtleText,
      fontSize: 12,
      marginBottom: 2,
    },
    replyPreviewLineMine: {
      color: theme.mineBubbleReplyMuted,
      fontSize: 12,
      marginBottom: 2,
    },
    replyPreviewLabel: {
      color: theme.subtleText,
      fontSize: 11,
      fontWeight: "700",
      marginBottom: 2,
    },
    replyPreviewLabelMine: {
      color: theme.mineBubbleReplyMuted,
      fontSize: 11,
      fontWeight: "700",
      marginBottom: 2,
    },
    replyQuoteBlock: {
      borderLeftWidth: 3,
      borderRadius: 8,
      paddingVertical: CHAT_XH_HALF,
      paddingHorizontal: CHAT_XH,
      marginBottom: CHAT_XH,
    },
    replyQuoteLabel: {
      fontSize: 11,
      fontWeight: "700",
      lineHeight: Math.round(11 * 1.35),
      marginBottom: CHAT_XH_HALF,
    },
    replyQuoteBody: {
      fontSize: 12,
      lineHeight: Math.round(12 * 1.35),
      marginBottom: 0,
    },
    replyContextCard: {
      borderLeftWidth: 3,
      borderLeftColor: theme.accent,
      backgroundColor: theme.divider,
      opacity: 0.78,
      borderRadius: 8,
      paddingVertical: CHAT_XH_HALF,
      paddingHorizontal: CHAT_XH,
      marginBottom: CHAT_XH,
    },
    replyContextCardMine: {
      borderLeftWidth: 3,
      borderLeftColor: theme.accent,
      backgroundColor: theme.replyContextMineBg,
      borderRadius: 8,
      paddingVertical: CHAT_XH_HALF,
      paddingHorizontal: CHAT_XH,
      marginBottom: CHAT_XH,
    },
    attachmentBubble: {
      borderWidth: 1,
      borderColor: theme.divider,
      borderRadius: 8,
      padding: CHAT_XH,
      marginBottom: CHAT_XH_HALF,
    },
    attachmentBubbleMine: {
      borderWidth: 1,
      borderColor: `${theme.mineBubbleText}33`,
      borderRadius: 8,
      padding: CHAT_XH,
      marginBottom: CHAT_XH_HALF,
    },
    voiceMessageCard: {
      minWidth: 248,
      maxWidth: "88%",
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    voicePlayRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      width: "100%",
    },
    voiceProgressColumn: {
      flex: 1,
      minWidth: 0,
      gap: 6,
    },
    voiceProgressTrack: {
      height: 5,
      borderRadius: 3,
      backgroundColor: theme.divider,
      overflow: "hidden",
      width: "100%",
    },
    voiceProgressFill: {
      height: "100%",
      backgroundColor: theme.accent,
    },
    voiceProgressFillMine: {
      height: "100%",
      backgroundColor: theme.mineBubbleText,
    },
    voiceTimeLabel: {
      fontSize: 11,
      fontWeight: "600",
      color: theme.subtleText,
    },
    voiceTimeLabelMine: {
      fontSize: 11,
      fontWeight: "600",
      color: `${theme.mineBubbleText}cc`,
    },
    inlineMediaPreview: {
      width: 130,
      height: 130,
      borderRadius: 8,
      marginBottom: 6,
      backgroundColor: theme.divider,
    },
    photoMessageImage: {
      borderRadius: 10,
      backgroundColor: theme.divider,
      marginBottom: 4,
      alignSelf: "flex-start",
    },
    photoMessageColumn: {
      flex: 1,
      minWidth: 0,
      alignItems: "flex-start",
    },
    photoMessageColumnMine: {
      flex: 1,
      minWidth: 0,
      alignItems: "flex-end",
    },
    photoMessageStack: {
      alignSelf: "flex-start",
      maxWidth: "100%",
    },
    photoMessageStackMine: {
      alignSelf: "flex-end",
      maxWidth: "100%",
    },
    photoMessageImageDetached: {
      borderRadius: 10,
      alignSelf: "flex-start",
      marginBottom: 0,
      overflow: "hidden",
    },
    photoMessageImageDetachedMine: {
      alignSelf: "flex-end",
    },
    videoMessageWrap: {
      position: "relative",
      borderRadius: 10,
      overflow: "hidden",
      alignSelf: "flex-start",
      backgroundColor: "#000000",
    },
    videoMessageWrapMine: {
      alignSelf: "flex-end",
    },
    videoMessageVideo: {
      borderRadius: 0,
    },
    videoOverlayText: {
      position: "absolute",
    },
    photoCaptionCard: {
      alignSelf: "flex-start",
      maxWidth: "100%",
      marginTop: 8,
      borderTopLeftRadius: 12,
      borderTopRightRadius: 12,
    },
    photoCaptionCardMine: {
      alignSelf: "flex-end",
      maxWidth: "100%",
      marginTop: 8,
      borderTopLeftRadius: 12,
      borderTopRightRadius: 12,
    },
    reactionTray: {
      position: "absolute",
      right: 8,
      bottom: -7,
      flexDirection: "row",
      alignItems: "center",
      gap: 2,
    },
    reactionTrayBelowPhoto: {
      flexDirection: "row",
      alignItems: "center",
      gap: 2,
      marginTop: 8,
      alignSelf: "flex-start",
    },
    reactionChipCompact: {
      minWidth: 12,
      height: 12,
      alignItems: "center",
      justifyContent: "center",
      position: "relative",
      overflow: "visible",
    },
    reactionChipCompactEmoji: {
      fontSize: 12,
      lineHeight: 12,
    },
    reactionCountBubble: {
      position: "absolute",
      top: -5,
      right: -7,
      minWidth: 11,
      height: 11,
      borderRadius: 6,
      paddingHorizontal: 2,
      backgroundColor: theme.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    reactionCountText: {
      color: "#FFFFFF",
      fontSize: 7,
      fontWeight: "700",
    },
    messageMeta: {
      color: theme.subtleText,
      fontSize: 11,
    },
    messageMetaOutside: {
      color: theme.subtleText,
      fontSize: 10,
      marginTop: 5,
      marginLeft: 4,
    },
    messageMetaOutsideMine: {
      color: theme.subtleText,
      fontSize: 10,
      marginTop: 5,
      marginRight: 4,
      textAlign: "right",
      alignSelf: "stretch",
    },
    failedMessageActions: {
      flexDirection: "row",
      gap: 12,
      marginTop: 6,
      marginLeft: 4,
    },
    failedMessageActionsMine: {
      justifyContent: "flex-end",
      marginRight: 4,
      marginLeft: 0,
    },
    failedMessageActionBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    failedMessageActionText: {
      color: theme.accent,
      fontSize: 12,
      fontWeight: "600",
    },
    failedMessageDeleteText: {
      color: theme.danger,
      fontSize: 12,
      fontWeight: "600",
    },
    chatMemberStripWrap: {
      paddingHorizontal: 12,
      paddingTop: 6,
      paddingBottom: 10,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.divider,
    },
    chatMemberStripCaption: {
      color: theme.subtleText,
      fontSize: 11,
      fontWeight: "600",
      marginBottom: 6,
    },
    chatMemberStripScroll: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingRight: 4,
    },
    chatMemberStripChip: {
      alignItems: "center",
      maxWidth: 72,
    },
    chatMemberStripName: {
      marginTop: 3,
      color: theme.subtleText,
      fontSize: 10,
      textAlign: "center",
      width: "100%",
    },
    replyBanner: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: theme.divider,
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 7,
      marginBottom: 6,
    },
    /** Same tonal treatment as reply preview strips (regular chat). */
    broadcastModeHintStrip: {
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 7,
      marginTop: 10,
      marginBottom: 6,
      borderBottomWidth: StyleSheet.hairlineWidth,
    },
    replyBannerText: {
      color: theme.text,
      flex: 1,
      marginRight: 8,
      fontSize: 12,
    },
    pendingChatMediaThumb: {
      width: 44,
      height: 44,
      borderRadius: 6,
      marginRight: 8,
    },
    replyBannerClose: {
      padding: 2,
    },
    chatComposerStack: {
      borderTopWidth: 1,
    },
    replyPreviewShell: {
      flexDirection: "row",
      alignItems: "flex-start",
      borderBottomWidth: StyleSheet.hairlineWidth,
      paddingLeft: 10,
      paddingVertical: 6,
      paddingRight: 4,
    },
    replyPreviewScroll: {
      flex: 1,
      minWidth: 0,
      maxHeight: 160,
    },
    replyPreviewScrollContent: {
      paddingBottom: 4,
      flexGrow: 1,
    },
    replyPreviewMeta: {
      fontSize: 11,
      fontWeight: "700",
      marginBottom: 4,
    },
    replyPreviewBody: {
      fontSize: 13,
      lineHeight: 18,
    },
    replyPreviewClose: {
      padding: 6,
      marginTop: -2,
    },
    voicePreviewActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    chatInputBar: {
      paddingTop: 8,
      flexDirection: "row",
      gap: 6,
      alignItems: "flex-end",
      backgroundColor: theme.background,
    },
    chatInputBarCompact: {
      gap: 8,
    },
    attachButton: {
      width: 36,
      height: 36,
      borderWidth: 1,
      borderColor: theme.divider,
      borderRadius: 18,
      alignItems: "center",
      justifyContent: "center",
    },
    attachButtonSmall: {
      width: 28,
      height: 28,
      borderWidth: 1,
      borderColor: theme.divider,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
    },
    attachButtonSmallActive: {
      backgroundColor: theme.accent,
      borderColor: theme.accent,
    },
    voiceRecordingStrip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.divider,
    },
    voiceRecordingDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: theme.danger,
    },
    chatInput: {
      flex: 1,
      borderWidth: 1,
      borderColor: theme.divider,
      borderRadius: 10,
      color: theme.text,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    chatInputMultiline: {
      flex: 1,
      flexGrow: 1,
      minWidth: 0,
      minHeight: 36,
      maxHeight: 160,
      borderWidth: 1,
      borderColor: theme.divider,
      borderRadius: 10,
      color: theme.text,
      paddingHorizontal: 12,
      paddingVertical: 8,
      fontSize: 16,
      lineHeight: 20,
    },
    chatInputMultilineCompact: {
      maxHeight: 180,
    },
    sendButton: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: theme.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    sendButtonChat: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    primaryButton: {
      backgroundColor: theme.accent,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
      alignItems: "center",
      justifyContent: "center",
      minWidth: 96,
    },
    primaryButtonText: {
      color: "#FFFFFF",
      fontWeight: "700",
    },
    modalScreen: {
      flex: 1,
      backgroundColor: theme.background,
      paddingHorizontal: 14,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 10,
    },
    friendRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 11,
      paddingHorizontal: 6,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.divider,
    },
    friendRowSelected: {
      backgroundColor: `${theme.accent}1A`,
      borderWidth: 2,
      borderColor: theme.accent,
      borderRadius: 12,
      marginVertical: 4,
      borderBottomWidth: 0,
    },
    friendRowLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    broadcastOptionRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      borderWidth: 1,
      borderColor: theme.accent,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginBottom: 10,
      backgroundColor: `${theme.accent}22`,
    },
    broadcastOptionText: {
      color: theme.accent,
      fontWeight: "700",
      fontSize: 15,
    },
    secondaryActionRow: {
      alignSelf: "flex-end",
      marginBottom: 8,
      paddingVertical: 4,
      paddingHorizontal: 8,
    },
    dropdownTrigger: {
      borderWidth: 1,
      borderColor: theme.divider,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginBottom: 8,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    dropdownMenu: {
      borderWidth: 1,
      borderColor: theme.divider,
      borderRadius: 10,
      marginBottom: 10,
      paddingHorizontal: 10,
      paddingVertical: 6,
      gap: 4,
    },
    dropdownItem: {
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: theme.divider,
    },
    subtleText: {
      color: theme.subtleText,
      fontSize: 13,
      marginBottom: 8,
    },
    selectedText: {
      color: theme.accent,
      fontSize: 13,
      marginBottom: 8,
      fontWeight: "700",
    },
    settingsOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.45)",
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 24,
      paddingVertical: 28,
    },
    menuOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.35)",
      justifyContent: "flex-start",
      alignItems: "flex-end",
      paddingTop: 52,
      paddingRight: 18,
    },
    menuCard: {
      borderRadius: 12,
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.divider,
      minWidth: 220,
      overflow: "hidden",
    },
    menuRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderBottomWidth: 1,
      borderBottomColor: theme.divider,
    },
    menuRowText: {
      color: theme.text,
      fontSize: 15,
    },
    settingsCard: {
      width: "100%",
      maxHeight: "80%",
      borderRadius: 12,
      backgroundColor: theme.background,
      padding: 16,
      borderWidth: 1,
      borderColor: theme.divider,
      gap: 12,
    },
    addMemberModalCard: {
      maxWidth: 440,
      width: "100%",
      maxHeight: "88%",
    },
    addMemberList: {
      maxHeight: 320,
      marginBottom: 8,
    },
    broadcastSaveModalCard: {
      maxWidth: 440,
      width: "100%",
      minHeight: 200,
      paddingVertical: 28,
      paddingHorizontal: 24,
      justifyContent: "center",
    },
    groupCreateModalCard: {
      maxWidth: 480,
      width: "100%",
      minHeight: 420,
      maxHeight: "92%",
      paddingVertical: 22,
      paddingHorizontal: 22,
      borderRadius: 16,
    },
    groupCreateModalScroll: {
      gap: 14,
      paddingBottom: 12,
    },
    groupCreateModalTitle: {
      fontSize: 22,
      fontWeight: "700",
      color: theme.text,
      textAlign: "center",
    },
    groupCreatePhotoPressable: {
      alignSelf: "center",
    },
    groupCreatePhotoCircle: {
      width: 132,
      height: 132,
      borderRadius: 66,
      overflow: "hidden",
      backgroundColor: theme.replyQuotedFromOtherBg,
      borderWidth: 2,
      borderColor: theme.divider,
      alignItems: "center",
      justifyContent: "center",
    },
    groupCreatePhotoImage: {
      width: "100%",
      height: "100%",
    },
    groupCreatePhotoPrompt: {
      marginTop: 6,
      paddingHorizontal: 10,
      color: theme.subtleText,
      fontSize: 13,
      textAlign: "center",
    },
    broadcastModalActionRow: {
      flexDirection: "row",
      gap: 12,
      width: "100%",
      marginTop: 4,
      alignItems: "stretch",
    },
    broadcastModalBtn: {
      flex: 1,
      minHeight: 48,
      borderRadius: 10,
      paddingHorizontal: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    broadcastModalBtnOutline: {
      borderWidth: 2,
      borderColor: theme.accent,
      backgroundColor: theme.background,
    },
    broadcastModalBtnOutlineText: {
      color: theme.accent,
      fontWeight: "700",
      fontSize: 16,
    },
    broadcastModalBtnPrimary: {
      backgroundColor: theme.accent,
    },
    broadcastModalBtnPrimaryText: {
      color: "#FFFFFF",
      fontWeight: "700",
      fontSize: 16,
    },
    inputAccessoryBar: {
      flexDirection: "row",
      justifyContent: "flex-end",
      alignItems: "center",
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.divider,
      backgroundColor: theme.background,
    },
    inputAccessoryBarButton: {
      paddingHorizontal: 16,
      paddingVertical: 8,
    },
    inputAccessoryBarButtonText: {
      color: theme.accent,
      fontWeight: "700",
      fontSize: 17,
    },
    broadcastSavePromptTitle: {
      color: theme.text,
      fontSize: 21,
      fontWeight: "700",
      textAlign: "center",
      marginBottom: 10,
    },
    broadcastSavePromptBody: {
      color: theme.subtleText,
      fontSize: 16,
      lineHeight: 24,
      textAlign: "center",
      marginBottom: 12,
    },
    reactionPickerRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
    },
    reactionChip: {
      borderWidth: 1,
      borderColor: theme.divider,
      borderRadius: 16,
      paddingVertical: 6,
      paddingHorizontal: 10,
    },
    reactionChipText: {
      fontSize: 20,
    },
    memberRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 8,
    },
    settingsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    themePickerOptionRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 12,
      paddingHorizontal: 4,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.divider,
    },
    themePickerOptionRowLast: {
      borderBottomWidth: 0,
    },
    settingsRowHint: {
      color: theme.subtleText,
      fontSize: 15,
    },
    addFriendRoot: {
      flex: 1,
      paddingHorizontal: 14,
    },
    addFriendCircleWrap: {
      alignItems: "center",
      justifyContent: "center",
    },
    addFriendBigButton: {
      alignItems: "center",
      justifyContent: "center",
    },
    addFriendBigButtonInner: {
      paddingHorizontal: 4,
      alignItems: "center",
      justifyContent: "center",
      maxWidth: "98%",
      width: "100%",
    },
    addFriendBigButtonText: {
      fontSize: 36,
      fontWeight: "800",
      textAlign: "center",
      lineHeight: 44,
      letterSpacing: 0.25,
      width: "100%",
    },
    addFriendProfileFullScreen: {
      flex: 1,
      position: "relative",
    },
    /** Counteracts `addFriendRoot` horizontal padding so the profile is full screen width. */
    addFriendProfileBleed: {
      marginHorizontal: -14,
      alignSelf: "stretch",
    },
    addFriendProfileHeroColumn: {
      flex: 1,
      width: "100%",
      minHeight: 0,
      justifyContent: "center",
      alignItems: "center",
    },
    addFriendNowFriendsTitle: {
      fontSize: 28,
      fontWeight: "800",
      textAlign: "center",
      lineHeight: 36,
      letterSpacing: 0.2,
    },
    addFriendProfileSoloName: {
      marginTop: 14,
      paddingHorizontal: 20,
      fontSize: 24,
      fontWeight: "700",
      textAlign: "center",
    },
    addFriendProfileImageOnlyWrap: {
      flex: 1,
      width: "100%",
      minHeight: 0,
      justifyContent: "center",
      alignItems: "center",
    },
    addFriendProfileImageOnly: {
      alignSelf: "center",
    },
    /** Bottom stack layer: avatar + name (under dim + Lottie). */
    addFriendCelebrationBase: {
      zIndex: 0,
      elevation: 0,
      justifyContent: "center",
      alignItems: "center",
    },
    addFriendCelebrationHeroInner: {
      alignItems: "stretch",
      justifyContent: "center",
      width: "100%",
    },
    /** Full-bleed width; letterboxing uses `theme.background` on frame. */
    addFriendCelebrationPhotoFrame: {
      overflow: "hidden",
      alignSelf: "stretch",
      width: "100%",
    },
    addFriendCelebrationNameOnAccent: {
      alignSelf: "center",
    },
    /** Dark scrim between photo and confetti. */
    addFriendCelebrationDim: {
      zIndex: 1,
      elevation: 1,
    },
    addFriendCelebrationLottieWrap: {
      zIndex: 2,
      elevation: 2,
    },
    addFriendCelebrationTitleWrap: {
      zIndex: 3,
      elevation: 3,
    },
    bioInput: {
      minHeight: 100,
      textAlignVertical: "top",
    },
  });
